services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: truebank_zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: truebank_kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"

  postgres-auth:
    image: postgres:15
    container_name: postgres-server-auth
    environment:
      POSTGRES_USER: true-server
      POSTGRES_PASSWORD: true123
      POSTGRES_DB: true_db_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth:/var/lib/postgresql/data

  postgres-transaction:
    image: postgres:15
    container_name: postgres-server-server
    environment:
      POSTGRES_USER: true-server
      POSTGRES_PASSWORD: true123
      POSTGRES_DB: true_db_transaction
    ports:
      - "5433:5432"
    volumes:
      - postgres_transaction:/var/lib/postgresql/data

  postgres-users:
    image: postgres:15
    container_name: postgres-server-user
    environment:
      POSTGRES_USER: true-server
      POSTGRES_PASSWORD: true123
      POSTGRES_DB: true_db_user
    ports:
      - "5434:5432"
    volumes:
      - postgres_user:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "1010:1010"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafkaService:9092
    depends_on:
      - kafka


volumes:
  postgres_auth:
  postgres_transaction:
  postgres_user:
  redis_data: