apiVersion: v1
data:
  JWT_SECRET: "my_true_secret_key"
  KAFKA_BROKER: "kafka:9092"
  KAFKA_BROKERS: "kafka:9092"
  USER_SERVICE_URL: "http://user-service:5050"
  TRANSACTION_SERVICE_URL: "http://transaction-service:6060"
  AUTH_SERVICE_URL: "http://auth-service:7070"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: api-gateway-api-gateway-env
  name: api-gateway-env
