apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\pasaz\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: auth-service
  name: auth-service
spec:
  ports:
    - name: "7070"
      port: 7070
      targetPort: 7070
    - name: "50051"
      port: 50051
      targetPort: 50051
  selector:
    io.kompose.service: auth-service
