apiVersion: v1
kind: Service
metadata:
  name: postgres-transaction
  labels:
    app: postgres-transaction
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: postgres-transaction
