apiVersion: v1
data:
  prometheus.yaml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'api-gateway'
        static_configs:
          - targets: ['api-gateway:8080']

      - job_name: 'auth-service'
        static_configs:
          - targets: ['auth-service:7070']

      - job_name: 'user-service'
        static_configs:
          - targets: ['user-service:5050']

      - job_name: 'transaction-service'
        static_configs:
          - targets: ['transaction-service:6060']
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
