apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\pasaz\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: promtail
  name: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: promtail
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\pasaz\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: promtail
    spec:
      containers:
        - args:
            - -config.file=/etc/promtail/promtail-config.yaml
          image: grafana/promtail:3.0.0
          name: promtail
          volumeMounts:
            - mountPath: /etc/promtail/promtail-config.yaml
              name: promtail-cm0
              subPath: promtail-config.yaml
            - mountPath: /var/log
              name: promtail-claim1
            - mountPath: /var/lib/docker/containers
              name: promtail-claim2
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: promtail-config.yaml
                path: promtail-config.yaml
            name: promtail-cm0
          name: promtail-cm0
        - name: promtail-claim1
          persistentVolumeClaim:
            claimName: promtail-claim1
        - name: promtail-claim2
          persistentVolumeClaim:
            claimName: promtail-claim2
