apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\pasaz\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: transaction-service
  name: transaction-service
spec:
  ports:
    - name: "6060"
      port: 6060
      targetPort: 6060
    - name: "50053"
      port: 50053
      targetPort: 50053
  selector:
    io.kompose.service: transaction-service
