apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-service-env
  labels:
    app: transaction-service
data:
  DB_DNS: "host=postgres-transaction user=true-server password=true123 dbname=true_db_transaction port=5432 sslmode=disable"
  RUN_MIGRATION: "true"
