apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\pasaz\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  ports:
    - name: "5050"
      port: 5050
      targetPort: 5050
    - name: "50052"
      port: 50052
      targetPort: 50052
  selector:
    io.kompose.service: user-service
